spring:
  application:
    name: TaskService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    url: jdbc:postgresql://localhost:5432/taskmanager
  jpa:
    properties:
      hibernate:
        default_schema: tasks
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9120
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:${EUREKAPORT}/eureka/
