spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
            locator:
              enabled: true
      routes:
        - id: auth-service
          uri: lb://AuthServer
          predicates:
            - Path=/auth/**
#
        - id: task-create
          uri: lb://TaskService
          predicates:
            - Path=/tasks/create
            - Method=POST
          filters:
            - name: JWTFilter
#
        - id: task-get
          uri: lb://TaskService
          predicates:
            - Path=/tasks/get
            - Method=GET
          filters:
            - name: JWTFilter
#
        - id: task-delete
          uri: lb://TaskService
          predicates:
            - Path=/tasks/delete
            - Method=DELETE
          filters:
            - name: JWTFilter
#
        - id: task-edit
          uri: lb://TaskService
          predicates:
            - Path=/tasks/edit
            - Method=PATCH
          filters:
            - name: JWTFilter
#
server:
  port: 5290
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:${EUREKAPORT}/eureka/
jwt:
  secret: ${JWT_SECRET}
