eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:${EUREKAPORT}/eureka/
server:
  port: 1266
spring:
  application:
    name: NotificationService
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest