eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:${EUREKAPORT}/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 1266
spring:
  application:
    name: NotificationService
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health, prometheus