scrape_configs:
  - job_name: 'TaskManagerMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9120',
                  'host.docker.internal:8081',
                  'host.docker.internal:8430',
                  'host.docker.internal:5920',]
        labels:
          application: 'TaskManager'